name: Code Coverage
on: [push, pull_request]

jobs:
  run_codecov:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{matrix. java}} 
        uses: actions/setup-java@v1 
        with:
          java-version: ${{matrix. java}}
      - name: Run test 
        run: mvn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./netty-rpc/target/site/jacoco/jacoco.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          

