name: Flomo Reminder
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  run_codecov:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

